### ISSUE TITLE
pip install cannot determine archive format

### ISSUE THREAD

**Issue by t-anton** [kanshao/bbmd#1]
Hi, I am unable to install the package on my local computer (macOS 10.14).

The message in Anaconda terminal is:

`bash-3.2$ python --version`    
`Python 3.7.1`
`bash-3.2$ pip install https://github.com/kanshao/bbmd`
`Collecting https://github.com/kanshao/bbmd`
`  Downloading https://github.com/kanshao/bbmd`
`     - 92kB 1.5MB/s`
`  Cannot unpack file /private/var/folders/yj/w344kmjn0954gt9b2rz3x8vh0000gp/T/pip-unpack-6jrnmtvo/bbmd (downloaded from /private/var/folders/yj/w344kmjn0954gt9b2rz3x8vh0000gp/T/pip-req-build-j1vx3340, content-type: text/html; charset=utf-8); cannot detect archive format
Cannot determine archive format of /private/var/folders/yj/w344kmjn0954gt9b2rz3x8vh0000gp/T/pip-req-build-j1vx3340`

The same message is reported in Ubuntu 18.04 and Windows 10. I run Ubuntu and Windows through Parallels Desktop.

**Comment by shapiromatron** [comment]
AFAIK, it's not possible to pip a git repository in this manner without us building extra dependencies; you'll need to clone the repo and then install from the setup.py.  

For example, after cloning the repository, you can write: `pip install -e ../path/to/setup.py`, and that should do the trick.

**Comment by t-anton** [comment]
A slightly different command started the installation process:

`pip instal -e /path/to/bbmd-master`

but it didn't finish. 
For some reason, both macOS and Ubuntu show:

`Failed building wheel for pystan`, and
`Failed building wheel for matplotlib`.

**Any help on this?**
BTW, I still didn't try Windows.

**Comment by shapiromatron** [comment]
I'm not sure, it looks like it's failing when building dependencies not bbmd itself, so this is out of scope for bbmd. Can you send more details? 

I suspect you'll have better luck on Ubuntu than windows; I develop on mac as an FYI.

**Comment by t-anton** [comment]
You are right, dependencies make a proble. 
**Can you please check my dependencies?**
**Also, can you post a list of required dependencies?**

$ **gcc --version**
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/c++/4.2.1
Apple LLVM version 10.0.0 (clang-1000.10.44.2)
Target: x86_64-apple-darwin18.0.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

**clang version 4.0.1** (tags/RELEASE_401/final)
Target: x86_64-apple-darwin18.0.0
Thread model: posix
InstalledDir: /anaconda3/bin

Here is a list of **Anaconda packages** installed on mac:

_ipyw_jlab_nb_ext_conf    0.1.0                    py37_0  
alabaster                 0.7.12                   py37_0  
anaconda                  2018.12                  py37_0  
anaconda-client           1.7.2                    py37_0  
anaconda-navigator        1.9.6                    py37_0  
anaconda-project          0.8.2                    py37_0  
appnope                   0.1.0                    py37_0  
asn1crypto                0.24.0                   py37_0  
astroid                   2.1.0                    py37_0  
astropy                   3.1              py37h1de35cc_0  
atomicwrites              1.2.1                    py37_0  
attrs                     18.2.0           py37h28b3542_0  
babel                     2.6.0                    py37_0  
backcall                  0.1.0                    py37_0  
backports                 1.0                      py37_1  
backports.os              0.1.1                    py37_0  
backports.shutil_get_terminal_size 1.0.0                    py37_2  
beautifulsoup4            4.6.3                    py37_0  
bitarray                  0.8.3            py37h1de35cc_0  
bkcharts                  0.2                      py37_0  
blas                      1.0                         mkl  
blaze                     0.11.3                   py37_0  
blessed                   1.15.0                   pypi_0    pypi
blosc                     1.14.4               hd9629dc_0  
bokeh                     1.0.2                    py37_0  
boto                      2.49.0                   py37_0  
bottleneck                1.2.1            py37h1d22016_1  
bzip2                     1.0.6                h1de35cc_5  
ca-certificates           2018.03.07                    0  
cctools                   895                           1  
certifi                   2018.11.29               py37_0  
cffi                      1.11.5           py37h6174b99_1  
chardet                   3.0.4                    py37_1  
clang                     4.0.1                         1  
clang_osx-64              4.0.1               h1ce6c1d_11  
clangxx                   4.0.1                         1  
clangxx_osx-64            4.0.1               h22b1bf0_11  
click                     7.0                      py37_0  
cloudpickle               0.6.1                    py37_0  
clyent                    1.2.2                    py37_1  
colorama                  0.4.1                    py37_0  
compiler-rt               4.0.1                hcfea43d_1  
conda                     4.6.1                    py37_0  
conda-build               3.17.6                   py37_0  
conda-env                 2.6.0                         1  
conda-verify              3.1.1                    py37_0  
contextlib2               0.5.5                    py37_0  
cryptography              2.4.2            py37ha12b0ac_0  
curl                      7.63.0            ha441bb4_1000  
cycler                    0.10.0                   py37_0  
cython                    0.29.2           py37h0a44026_0  
cytoolz                   0.9.0.1          py37h1de35cc_1  
dask                      1.0.0                    py37_0  
dask-core                 1.0.0                    py37_0  
datashape                 0.5.4                    py37_1  
datatable                 0.7.0                    pypi_0    pypi
dbus                      1.13.2               h760590f_1  
decorator                 4.3.0                    py37_0  
defusedxml                0.5.0                    py37_1  
distributed               1.25.1                   py37_0  
docutils                  0.14                     py37_0  
entrypoints               0.2.3                    py37_2  
et_xmlfile                1.0.1                    py37_0  
expat                     2.2.6                h0a44026_0  
fastcache                 1.0.2            py37h1de35cc_2  
filelock                  3.0.10                   py37_0  
flask                     1.0.2                    py37_1  
flask-cors                3.0.7                    py37_0  
freetype                  2.9.1                hb4e5f40_0  
future                    0.17.1                   py37_0  
get_terminal_size         1.0.0                h7520d66_0  
gettext                   0.19.8.1             h15daf44_3  
gevent                    1.3.7            py37h1de35cc_1  
glib                      2.56.2               hd9629dc_0  
glob2                     0.6                      py37_1  
gmp                       6.1.2                hb37e062_1  
gmpy2                     2.0.8            py37h6ef4df4_2  
greenlet                  0.4.15           py37h1de35cc_0  
h5py                      2.8.0            py37h878fce3_3  
hdf5                      1.10.2               hfa1e0ec_1  
heapdict                  1.0.0                    py37_2  
html5lib                  1.0.1                    py37_0  
icu                       58.2                 h4b95b61_1  
idna                      2.8                      py37_0  
imageio                   2.4.1                    py37_0  
imagesize                 1.1.0                    py37_0  
importlib_metadata        0.6                      py37_0  
intel-openmp              2019.1                      144  
ipykernel                 5.1.0            py37h39e3cac_0  
ipython                   7.2.0            py37h39e3cac_0  
ipython_genutils          0.2.0                    py37_0  
ipywidgets                7.4.2                    py37_0  
isort                     4.3.4                    py37_0  
itsdangerous              1.1.0                    py37_0  
jbig                      2.1                  h4d881f8_0  
jdcal                     1.4                      py37_0  
jedi                      0.13.2                   py37_0  
jinja2                    2.10                     py37_0  
jpeg                      9b                   he5867d9_2  
jsonschema                2.6.0                    py37_0  
jupyter                   1.0.0                    py37_7  
jupyter_client            5.2.4                    py37_0  
jupyter_console           6.0.0                    py37_0  
jupyter_core              4.4.0                    py37_0  
jupyterlab                0.35.3                   py37_0  
jupyterlab_server         0.2.0                    py37_0  
keyring                   17.0.0                   py37_0  
kiwisolver                1.0.1            py37h0a44026_0  
krb5                      1.16.1               hddcf347_7  
lazy-object-proxy         1.3.1            py37h1de35cc_2  
ld64                      274.2                         1  
libarchive                3.3.3                h786848e_5  
libcurl                   7.63.0            h051b688_1000  
libcxx                    4.0.1                hcfea43d_1  
libcxxabi                 4.0.1                hcfea43d_1  
libedit                   3.1.20170329         hb402a30_2  
libffi                    3.2.1                h475c297_4  
libgfortran               3.0.1                h93005f0_2  
libiconv                  1.15                 hdd342a3_7  
liblief                   0.9.0                h2a1bed3_0  
libpng                    1.6.35               ha441bb4_0  
libsodium                 1.0.16               h3efe00b_0  
libssh2                   1.8.0                ha12b0ac_4  
libtiff                   4.0.9                hcb84e12_2  
libxml2                   2.9.8                hab757c2_1  
libxslt                   1.1.32               hb819dd2_0  
llvm                      4.0.1                         1  
llvm-lto-tapi             4.0.1                         1  
llvmlite                  0.26.0           py37h8c7ce04_0  
locket                    0.2.0                    py37_1  
lxml                      4.2.5            py37hef8c89e_0  
lz4-c                     1.8.1.2              h1de35cc_0  
lzo                       2.10                 h362108e_2  
markupsafe                1.1.0            py37h1de35cc_0  
matplotlib                3.0.2            py37h54f8f79_0  
mccabe                    0.6.1                    py37_1  
mistune                   0.8.4            py37h1de35cc_0  
mkl                       2019.1                      144  
mkl-service               1.1.2            py37hfbe908c_5  
mkl_fft                   1.0.6            py37h27c97d8_0  
mkl_random                1.0.2            py37h27c97d8_0  
more-itertools            4.3.0                    py37_0  
mpc                       1.1.0                h6ef4df4_1  
mpfr                      4.0.1                h3018a27_3  
mpmath                    1.1.0                    py37_0  
msgpack-python            0.5.6            py37h04f5b5a_1  
multipledispatch          0.6.0                    py37_0  
navigator-updater         0.2.1                    py37_0  
nbconvert                 5.4.0                    py37_1  
nbformat                  4.4.0                    py37_0  
ncurses                   6.1                  h0a44026_1  
networkx                  2.2                      py37_1  
nltk                      3.4                      py37_1  
nodejs                    10.13.0              h0a44026_0    anaconda
nose                      1.3.7                    py37_2  
notebook                  5.7.4                    py37_0  
numba                     0.41.0           py37h6440ff4_0  
numexpr                   2.6.8            py37h7413580_0  
numpy                     1.15.4           py37hacdab7b_0  
numpy-base                1.15.4           py37h6575580_0  
numpydoc                  0.8.0                    py37_0  
odo                       0.5.1                    py37_0  
olefile                   0.46                     py37_0  
openpyxl                  2.5.12                   py37_0  
openssl                   1.1.1a               h1de35cc_0  
packaging                 18.0                     py37_0  
pandas                    0.23.4           py37h6440ff4_0  
pandoc                    1.19.2.1             ha5e8f32_1  
pandocfilters             1.4.2                    py37_1  
parso                     0.3.1                    py37_0  
partd                     0.3.9                    py37_0  
path.py                   11.5.0                   py37_0  
pathlib2                  2.3.3                    py37_0  
patsy                     0.5.1                    py37_0  
pcre                      8.42                 h378b8a2_0  
pep8                      1.7.1                    py37_0  
pexpect                   4.6.0                    py37_0  
pickleshare               0.7.5                    py37_0  
pillow                    5.3.0            py37hb68e598_0  
pip                       18.1                     py37_0  
pkg-config                0.29.2               h3efe00b_8  
pkginfo                   1.4.2                    py37_1  
pluggy                    0.8.0                    py37_0  
ply                       3.11                     py37_0  
prometheus_client         0.5.0                    py37_0  
prompt_toolkit            2.0.7                    py37_0  
psutil                    5.4.8            py37h1de35cc_0  
ptyprocess                0.6.0                    py37_0  
py                        1.7.0                    py37_0  
py-lief                   0.9.0            py37hd4eaf27_0  
pycodestyle               2.4.0                    py37_0  
pycosat                   0.6.3            py37h1de35cc_0  
pycparser                 2.19                     py37_0  
pycrypto                  2.6.1            py37h1de35cc_9  
pycurl                    7.43.0.2         py37ha12b0ac_0  
pyflakes                  2.0.0                    py37_0  
pygments                  2.3.1                    py37_0  
pylint                    2.2.2                    py37_0  
pyodbc                    4.0.25           py37h0a44026_0  
pyopenssl                 18.0.0                   py37_0  
pyparsing                 2.3.0                    py37_0  
pyqt                      5.9.2            py37h655552a_2  
pysocks                   1.6.8                    py37_0  
pystan                    2.18.0.0         py37h6440ff4_0  
pytables                  3.4.4            py37h13cba08_0  
pytest                    4.0.2                    py37_0  
pytest-arraydiff          0.3              py37h39e3cac_0  
pytest-astropy            0.5.0                    py37_0  
pytest-doctestplus        0.2.0                    py37_0  
pytest-openfiles          0.3.1                    py37_0  
pytest-remotedata         0.3.1                    py37_0  
python                    3.7.1                haf84260_7  
python-dateutil           2.7.5                    py37_0  
python-libarchive-c       2.8                      py37_6  
python.app                2                        py37_9  
pytz                      2018.7                   py37_0  
pywavelets                1.0.1            py37h1d22016_0  
pyyaml                    3.13             py37h1de35cc_0  
pyzmq                     17.1.2           py37h1de35cc_0  
qt                        5.9.7                h468cd18_1  
qtawesome                 0.5.3                    py37_0  
qtconsole                 4.4.3                    py37_0  
qtpy                      1.5.2                    py37_0  
readline                  7.0                  h1de35cc_5  
requests                  2.21.0                   py37_0  
rope                      0.11.0                   py37_0  
rpy2                      2.9.5                    pypi_0    pypi
ruamel_yaml               0.15.46          py37h1de35cc_0  
scikit-image              0.14.1           py37h0a44026_0  
scikit-learn              0.20.1           py37h27c97d8_0  
scipy                     1.1.0            py37h1410ff5_2  
seaborn                   0.9.0                    py37_0  
send2trash                1.5.0                    py37_0  
setuptools                40.6.3                   py37_0  
simplegeneric             0.8.1                    py37_2  
singledispatch            3.4.0.3                  py37_0  
sip                       4.19.8           py37h0a44026_0  
six                       1.12.0                   py37_0  
snappy                    1.1.7                he62c110_3  
snowballstemmer           1.2.1                    py37_0  
sortedcollections         1.0.1                    py37_0  
sortedcontainers          2.1.0                    py37_0  
sphinx                    1.8.2                    py37_0  
sphinxcontrib             1.0                      py37_1  
sphinxcontrib-websupport  1.1.0                    py37_1  
spyder                    3.3.2                    py37_0  
spyder-kernels            0.3.0                    py37_0  
sqlalchemy                1.2.15           py37h1de35cc_0  
sqlite                    3.26.0               ha441bb4_0  
statsmodels               0.9.0            py37h1d22016_0  
sympy                     1.3                      py37_0  
tblib                     1.3.2                    py37_0  
terminado                 0.8.1                    py37_1  
testpath                  0.4.2                    py37_0  
tk                        8.6.8                ha441bb4_0  
toolz                     0.9.0                    py37_0  
tornado                   5.1.1            py37h1de35cc_0  
tqdm                      4.28.1           py37h28b3542_0  
traitlets                 4.3.2                    py37_0  
typesentry                0.2.7                    pypi_0    pypi
tzlocal                   1.5.1                    pypi_0    pypi
unicodecsv                0.14.1                   py37_0  
unixodbc                  2.3.7                h1de35cc_0  
urllib3                   1.24.1                   py37_0  
wcwidth                   0.1.7                    py37_0  
webencodings              0.5.1                    py37_1  
werkzeug                  0.14.1                   py37_0  
wheel                     0.32.3                   py37_0  
widgetsnbextension        3.4.2                    py37_0  
wrapt                     1.10.11          py37h1de35cc_2  
wurlitzer                 1.0.2                    py37_0  
xlrd                      1.2.0                    py37_0  
xlsxwriter                1.1.2                    py37_0  
xlwings                   0.15.1                   py37_0  
xlwt                      1.3.0                    py37_0  
xz                        5.2.4                h1de35cc_4  
yaml                      0.1.7                hc338f04_2  
zeromq                    4.2.5                h0a44026_1  
zict                      0.1.3                    py37_0  
zlib                      1.2.11               h1de35cc_3  
zstd                      1.3.7                h5bba6e5_0

**Comment by shapiromatron** [comment]
Sorry, that's too specific; requirements aren't that exact. What are the errors you're getting with pystan and matplotlib?   Not just the wheel failed, but more details?

**Comment by shapiromatron** [comment]
try running `pip install -U pip` before the `pip install -e path/to/setup.py` ...

**Comment by t-anton** [comment]
Hi, I was able to get the complete output. It is ~2000 pages long :). 
It seems to me that the problem is in `C` compilation. 
Here is a small portion related to the pystan:

`building 'pystan._misc' extension`
  `C compiler: x86_64-apple-darwin13.4.0-clang -DNDEBUG -fwrapv -O3 -Wall -Wstrict-prototypes -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -D_FORTIFY_SOURCE=2 -mmacosx-version-min=10.9`
  
  `compile options: '-I/anaconda3/include/python3.7m -c'`
  `x86_64-apple-darwin13.4.0-clang: pystan/_misc.cpp`
  `pystan/_misc.cpp:15662:65: error: too many arguments to function call, expected 3, have 4
      return (*((__Pyx_PyCFunctionFast)meth)) (self, args, nargs, NULL);`
             `~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                     ^~~~`
  `/anaconda3/bin/../lib/clang/4.0.1/include/stddef.h:100:18: note: expanded from macro 'NULL'`
  `#    define NULL __null`
                   `^~~~~~`
  `pystan/_misc.cpp:17245:21: error: no member named 'exc_type' in '_ts'`
      `*type = tstate->exc_type;`
              `~~~~~~  ^`
  `pystan/_misc.cpp:17246:22: error: no member named 'exc_value' in '_ts'; did you mean 'curexc_value'?`
      `*value = tstate->exc_value;`
                       `^~~~~~~~~`
                       `curexc_value`
  `/anaconda3/include/python3.7m/pystate.h:240:15: note: 'curexc_value' declared here`
      `PyObject *curexc_value;`
               ` ^`
  `pystan/_misc.cpp:17247:19: error: no member named 'exc_traceback' in '_ts'; did you mean 'curexc_traceback'?`
      `*tb = tstate->exc_traceback;`
                    `^~~~~~~~~~~~~`
                    `curexc_traceback`
 ` /anaconda3/include/python3.7m/pystate.h:241:15: note: 'curexc_traceback' declared here`
      `PyObject *curexc_traceback;`
                `^`
 `pystan/_misc.cpp:17254:24: error: no member named 'exc_type' in '_ts'`
      `tmp_type = tstate->exc_type;`
                 `~~~~~~  ^`
  `pystan/_misc.cpp:17255:25: error: no member named 'exc_value' in '_ts'; did you mean 'curexc_value'?`
      `tmp_value = tstate->exc_value;`
                          `^~~~~~~~~`
                          `curexc_value`
  `/anaconda3/include/python3.7m/pystate.h:240:15: note: 'curexc_value' declared here`
      `PyObject *curexc_value;`
                `^`
  `pystan/_misc.cpp:17256:22: error: no member named 'exc_traceback' in '_ts'; did you mean` `'curexc_traceback'?`
      `tmp_tb = tstate->exc_traceback;`
                       `^~~~~~~~~~~~~`
                      ` curexc_traceback`
  `/anaconda3/include/python3.7m/pystate.h:241:15: note: 'curexc_traceback' declared here`
      `PyObject *curexc_traceback;`
               `^`
  `pystan/_misc.cpp:17257:13: error: no member named 'exc_type' in '_ts'`
      `tstate->exc_type = type;`
      `~~~~~~  ^`
  `pystan/_misc.cpp:17258:13: error: no member named 'exc_value' in '_ts'; did you mean 'curexc_value'?`
      `tstate->exc_value = value;`
             `^~~~~~~~~`
              `curexc_value`
  `/anaconda3/include/python3.7m/pystate.h:240:15: note: 'curexc_value' declared here`
      `PyObject *curexc_value;`
                `^`
  `pystan/_misc.cpp:17259:13: error: no member named 'exc_traceback' in '_ts'; did you mean 'curexc_traceback'?`
      `tstate->exc_traceback = tb;`
              `^~~~~~~~~~~~~`
              `curexc_traceback`
  `/anaconda3/include/python3.7m/pystate.h:241:15: note: 'curexc_traceback' declared here`
      `PyObject *curexc_traceback;`
               `^`
  `pystan/_misc.cpp:17314:24: error: no member named 'exc_type' in '_ts'`
      `tmp_type = tstate->exc_type;`
                 `~~~~~~  ^`
  `pystan/_misc.cpp:17315:25: error: no member named 'exc_value' in '_ts'; did you mean 'curexc_value'?`
      `tmp_value = tstate->exc_value;`
                          `^~~~~~~~~`
                          `curexc_value`
  `/anaconda3/include/python3.7m/pystate.h:240:15: note: 'curexc_value' declared here`
      `PyObject *curexc_value;`
                `^`
  `pystan/_misc.cpp:17316:22: error: no member named 'exc_traceback' in '_ts'; did you mean` `'curexc_traceback'?`
      `tmp_tb = tstate->exc_traceback;`
                       `^~~~~~~~~~~~~`
                       `curexc_traceback`
  `/anaconda3/include/python3.7m/pystate.h:241:15: note: 'curexc_traceback' declared here`
      `PyObject *curexc_traceback;`
                `^`
  `pystan/_misc.cpp:17317:13: error: no member named 'exc_type' in '_ts'`
      `tstate->exc_type = local_type;`
      `~~~~~~  ^`
  `pystan/_misc.cpp:17318:13: error: no member named 'exc_value' in '_ts'; did you mean 'curexc_value'?`
      `tstate->exc_value = local_value;`
              `^~~~~~~~~`
              `curexc_value`
  `/anaconda3/include/python3.7m/pystate.h:240:15: note: 'curexc_value' declared here`
      `PyObject *curexc_value;`
                `^`
  `pystan/_misc.cpp:17319:13: error: no member named 'exc_traceback' in '_ts'; did you mean 'curexc_traceback'?`
      `tstate->exc_traceback = local_tb;`
              `^~~~~~~~~~~~~`
              `curexc_traceback`
  `/anaconda3/include/python3.7m/pystate.h:241:15: note: 'curexc_traceback' declared here`
      `PyObject *curexc_traceback;`
                `^`
  `pystan/_misc.cpp:17341:24: error: no member named 'exc_type' in '_ts'`
      `tmp_type = tstate->exc_type;`
                 `~~~~~~  ^`
  `pystan/_misc.cpp:17342:25: error: no member named 'exc_value' in '_ts'; did you mean 'curexc_value'?`
      `tmp_value = tstate->exc_value;`
                          `^~~~~~~~~`
                          `curexc_value`
  `/anaconda3/include/python3.7m/pystate.h:240:15: note: 'curexc_value' declared here`
      `PyObject *curexc_value;`
                `^`
  `pystan/_misc.cpp:17343:22: error: no member named 'exc_traceback' in '_ts'; did you mean 'curexc_traceback'?`
      `tmp_tb = tstate->exc_traceback;`
                       `^~~~~~~~~~~~~`
                       `curexc_traceback`
  `/anaconda3/include/python3.7m/pystate.h:241:15: note: 'curexc_traceback' declared here`
      `PyObject *curexc_traceback;`
                `^`
  `fatal error: too many errors emitted, stopping now [-ferror-limit=]`
  `20 errors generated.`
`error: Command "x86_64-apple-darwin13.4.0-clang -DNDEBUG -fwrapv -O3 -Wall -Wstrict-prototypes -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -D_FORTIFY_SOURCE=2 -mmacosx-version-min=10.9 -I/anaconda3/include/python3.7m -c pystan/_misc.cpp -o build/temp.macosx-10.9-x86_64-3.7/pystan/_misc.o" failed with exit status 1`
  
  `----------------------------------------`
  `Failed building wheel for pystan`
  `Running setup.py clean for pystan`
  `Building wheel for matplotlib (setup.py) ... error`

**Comment by shapiromatron** [comment]
Sorry, I'll be unable to help here; it's installed fine for me on ubuntu 18 and mac.
